apiVersion: v2
name: ai-form-assistant-showcase
version: 0.1.5
kubeVersion: ">= 1.13.0"
description: AI Form Assistant Showcase
type: application
keywords:
  - nodejs
  - javascript
  - typescript
  - docker
  - vue
home: https://bcgov.github.io/ai-form-assistant-showcase
sources:
  - https://github.com/bcgov/ai-form-assistant-showcase
dependencies: []
maintainers:
  - name: NR Common Service Showcase Team
    email: NR.CommonServiceShowcase@gov.bc.ca
appVersion: "0.1.0"
deprecated: false
annotations: {}
